name: todolist
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  google_sign_in: ^4.5.5
  intl: ^0.16.1
  ndialog: ^3.1.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.10
  shimmer: ^1.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
